#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    value = arr[-1]
    sorted_arr = sorted(arr)
    
    for i in arr[-2::-1]:
        if arr == sorted_arr:
            break
        elif i > value:
            arr[arr.index(i) + 1] = i
        else:
            arr[arr.index(i) + 1] = value
        print(*arr)
    else:
        if arr != sorted_arr: 
            arr[0] = value
            print(*arr)
  

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
